Introduction to Numpy


In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array((1,2,3,4,5))

print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
c=np.array([[1,2,3],[2,3,4]])
print(c.ndim)

2


In [7]:
d=np.array([[[1,2,3],[4,5,6]],[[3,4,5],[6,7,8]]])

In [8]:
print(d.shape[0],d.shape[1],d.shape[2])

2 2 3


In [12]:
print(d[1,0,2])


5


In [13]:
d.size  #this give the number of elements present in the array

12

In [15]:
d.nbytes #hence each of the integer takes 4 bytes so total 12*4

48

In [21]:

A=np.arange(10)
print(A)

[0 1 2 3 4 5 6 7 8 9]
